CREATE TABLE Health_History
(
Patient_ID VARCHAR2 (100) PRIMARY KEY,
Health_Issue VARCHAR2 (100),
Appointment_date Date,
Hospital_name VARCHAR2 (100),
Doctor VARCHAR2 (100)

);

CREATE TABLE Foster_Parents
(
Foster_NID VARCHAR2 (100) PRIMARY KEY,
Foster_Father VARCHAR2 (100),
Foster_Mother VARCHAR2 (100),
Foster_Phone VARCHAR2 (100),
Foster_Address VARCHAR2 (100),
FOSTER_PASSWORD VARCHAR2 (100)

);

INSERT INTO Health_History (Patient_ID, Health_Issue ,Appointment_date, Hospital_name, Doctor) VALUES ('P_000001','Vitamin D deficiency', to_date('10-11-2019','DD-MM-YYYY'), 'Evercare Hospital', 'Rashidul Islam');


INSERT INTO Foster_Parents(Foster_NID, Foster_Father ,Foster_Mother, Foster_Phone, Foster_Address, FOSTER_PASSWORD) VALUES ('Foster_000002','Enamul Bijoy', 'Lara hoque', '01955966517', '13/A, Siddheswari Lane, Dhaka','F01');

select * from Foster_Parents;
select * from Health_History;
select * from EMPLOYEE;

DROP TABLE  Foster_Parents;
DROP TABLE  ADOPTION;
DROP TABLE  EMPLOYEE;
DROP TABLE  SUPERVISOR;




CREATE TABLE ADOPTION
(

ADOPTION_ID VARCHAR2(100) PRIMARY KEY ,
Foster_NID VARCHAR2 (100) NOT NULL ,
Court_Reference VARCHAR2 (100),
Adoption_Date DATE 

);
ALTER TABLE ADOPTION ADD FOREIGN KEY(FOSTER_NID) REFERENCES FOSTER_PARENTS (FOSTER_NID);


CREATE TABLE  EMPLOYEE
   (
    EMPLOYEE_ID VARCHAR2(100) PRIMARY KEY , 
	Emp_Name VARCHAR2(100),
    Emp_Department VARCHAR2(100),
    Emp_Designation VARCHAR2(100),
    Emp_Joining_date DATE,
    Salary NUMBER,
    Years_of_working NUMBER,
    EMPLOYEE_PASSWORD VARCHAR2 (100)

   ) ;
   
   
   CREATE TABLE SUPERVISOR
   (
    EMPLOYEE_ID VARCHAR2(100) PRIMARY KEY, 
	Emp_Name VARCHAR2(100),
    Emp_Department VARCHAR2(100),
    Emp_Designation VARCHAR2(100),
    Emp_Joining_date DATE,
    Salary NUMBER,
    Years_of_working NUMBER,
    EMPLOYEE_PASSWORD VARCHAR2 (100),
    Supervisor_Role VARCHAR2(100), 
    No_Of_child_supervision NUMBER

   ) ;

ALTER TABLE SUPERVISOR ADD FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID);


CREATE TABLE  CHILDREN_INFORMATION 
   (
    CHILD_ID VARCHAR2(100) PRIMARY KEY , 
	 
	CHILD_NAME VARCHAR2(100), 
	CHILD_AGE NUMBER, 
	CHILD_BED_NO VARCHAR(100), 
	CHILD_GENDER VARCHAR2(100), 
	CHILD_HEALTH_CONDITION VARCHAR2(100), 
	CHILD_INSTITUTION_NAME VARCHAR2(100), 
	CHILD_CLASS NUMBER, 
	CHILD_NATURE VARCHAR2(100), 
	ADDRESSING_DATE DATE ,
    EMPLOYEE_ID VARCHAR2 (100) NOT NULL ,
    ADOPTION_ID VARCHAR2 (100)  
    
   ) ;
ALTER TABLE CHILDREN_INFORMATION ADD FOREIGN KEY(ADOPTION_ID)  REFERENCES ADOPTION(ADOPTION_ID);
ALTER TABLE CHILDREN_INFORMATION ADD FOREIGN KEY(EMPLOYEE_ID)  REFERENCES SUPERVISOR(EMPLOYEE_ID);


CREATE TABLE CHILDREN_Health_TRACK
(
Patient_ID VARCHAR2 (100),
CHILD_ID VARCHAR2 (100)

);

ALTER TABLE CHILDREN_HEALTH_TRACK ADD FOREIGN KEY(PATIENT_ID)  REFERENCES HEALTH_HISTORY(PATIENT_ID);
ALTER TABLE CHILDREN_INFORMATION ADD FOREIGN KEY(CHILD_ID)  REFERENCES 
CHILDREN_INFORMATION(CHILD_ID);
